

export const GET_MISSIONS = 'GET_MISSIONS';
export const GET_MISSIONS_SUCCESS = 'GET_MISSIONS_SUCCESS';
export const GET_MISSIONS_ERROR = 'GET_MISSIONS_ERROR';

export const ADD_MISSIONS = 'ADD_MISSIONS';
export const ADD_MISSIONS_SUCCESS = 'ADD_MISSIONS_SUCCESS';
export const ADD_MISSIONS_ERROR = 'ADD_MISSIONS_ERROR';
